# Generated by Django 2.1.2 on 2019-03-28 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.CharField(blank=True, max_length=9, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('sexual_preference', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('income', models.CharField(blank=True, max_length=9, null=True)),
                ('abilities', models.TextField(blank=True, null=True)),
                ('relationship_skills', models.TextField(blank=True, null=True)),
                ('album', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Album')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('race', models.CharField(blank=True, max_length=20, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=20, null=True)),
                ('skin_color', models.CharField(blank=True, max_length=20, null=True)),
                ('face_shape', models.TextField(blank=True, null=True)),
                ('distinguishing_features', models.TextField(blank=True, null=True)),
                ('mannerism', models.TextField(blank=True, null=True)),
                ('habits', models.TextField(blank=True, null=True)),
                ('health', models.TextField(blank=True, null=True)),
                ('speech_patterns', models.CharField(blank=True, max_length=20, null=True)),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterPsychology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intelligence_level', models.CharField(blank=True, max_length=255, null=True)),
                ('mental_illnesses', models.TextField(blank=True, null=True)),
                ('learning_experiences', models.TextField(blank=True, null=True)),
                ('short_term_goals', models.TextField(blank=True, null=True)),
                ('long_term_goals', models.TextField(blank=True, null=True)),
                ('self_perception', models.TextField(blank=True, null=True)),
                ('perceived_by_others', models.TextField(blank=True, null=True)),
                ('self_confidence', models.CharField(blank=True, max_length=255, null=True)),
                ('emotionality', models.TextField(blank=True, null=True)),
                ('shame', models.TextField(blank=True, null=True)),
                ('mental_strengths', models.TextField(blank=True, null=True)),
                ('mental_weaknesses', models.TextField(blank=True, null=True)),
                ('attitude_type', models.CharField(blank=True, choices=[('Extravert', 'Extravert'), ('Introvert', 'Introvert')], max_length=15, null=True)),
                ('deals_with_anger', models.TextField(blank=True, null=True)),
                ('deals_with_sadness', models.TextField(blank=True, null=True)),
                ('deals_with_conflict', models.TextField(blank=True, null=True)),
                ('deals_with_change', models.TextField(blank=True, null=True)),
                ('deals_with_loss', models.TextField(blank=True, null=True)),
                ('movations', models.TextField(blank=True, null=True)),
                ('fears', models.TextField(blank=True, null=True)),
                ('pleasures', models.TextField(blank=True, null=True)),
                ('spiritual_beliefs', models.TextField(blank=True, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='characters.Character')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
    ]
